### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by wmertens** [NoamELB/react-hot-loader-loader#1]
I am doing bundle splitting with `react-universal-component` and it messes with RHL, so I figured I'd just run this plugin on all `\.jsx$` files.

This seems to work, but when I visit a page component that's behind a lazy import, it crashes.

```
hot.dev.js:31 Uncaught TypeError: Cannot call a class as a function
    at _classCallCheck (hot.dev.js:31)
    at ExportedComponent (hot.dev.js:85)
    at Object.<anonymous> (ReactSelect.jsx:21)
    at Object../src/components/Inputs/ReactSelect.jsx (ReactSelect.jsx:220)
    at __webpack_require__ (bootstrap 6d9f93b76456cb7e227a:707)
    at fn (bootstrap 6d9f93b76456cb7e227a:112)
    at Object.<anonymous> (SectionSelect.jsx:66)
    at Object../src/components/Inputs/SelectInput.jsx (SelectInput.jsx:7)
    at __webpack_require__ (bootstrap 6d9f93b76456cb7e227a:707)
    at fn (bootstrap 6d9f93b76456cb7e227a:112)
```

The wrapped code looks like
```
var reactAppToMakeSuperHot = StyledTagSelect;

var _default = Object(__WEBPACK_IMPORTED_MODULE_0_react_hot_loader__["hot"])(module)(reactAppToMakeSuperHot);
```

**Comment by NoamELB** [comment]
Thanks for reporting this!
I will check it out.

**Comment by theKashey** [comment]
`reactAppToMakeSuperHot` should be a React.Component, and it will produce a React.Component. As I could see - next you calling that "component" as a function, and that's generating an error.

**Comment by NoamELB** [comment]
@wmertens Can you give more details about "StyledTagSelect" in your example? Is it a React.Component or a function?
Maybe react-universal-component wraps it with a function?

**Comment by wmertens** [comment]
That could indeed be the problem, that it's a pure function component and not a React.Component class. So the approach of simply wrapping everything doesn't work, at least not in my case, I use a lot of pure function components and possibly styled-components returns one (StyledTagSelect in this case).
I will just close this then, thanks!

**Comment by theKashey** [comment]
Are you using functions not as elements? Could you provide some code?
